name: Test

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  unit:
    name: Unit Tests
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, macos-26-intel]
        python: [3.11, 3.13]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: pip install -r "ShellyNGMQTT.indigoPlugin/Contents/Server Plugin/requirements.txt" pytest-cov git+https://github.com/AaronLionsheep/pytest-indigo.git@skeleton
      
      - name: Test
        run: pytest

  install-dependencies:
    name: Install Dependencies
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, macos-26-intel]
        python: [3.11, 3.13]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        pip install -r "ShellyNGMQTT.indigoPlugin/Contents/Server Plugin/requirements.txt" --report install.json

    # Require all packages from from pre-build wheels, except for known packages
    # - A package that no longer provides a binary should be investigated (ex: cryptography dropping macos-x64 support)
    # - A new package that does not include a binary should be known since this may complicate plugin installation
    - name: Audit dependencies built from source
      run: |
        COMPILED=$(jq '
          [
            .install[] |
            select(.download_info.url | endswith(".whl") | not) |
            .metadata.name
          ] - [
            "bluetooth-data-tools",
            "habluetooth",
            "PyRIC"
          ]
        ' install.json)
        
        echo "Packages compiled unexpectedly: $COMPILED"
        echo "$COMPILED" | jq -e '. == []'
